### ISSUE TITLE
Consent

### ISSUE THREAD

**Issue by mustofa-id** [ssecd/jkn#6]
Pengembangan library ini bertujuan untuk mempermudah developer lain dalam melakukan integrasi atau bridging aplikasi dengan web service BPJS namun pengembangan ini akan membuat web service BPJS menjadi terbuka dan dapat diakses oleh siapa pun. Sementara baik mitra fasilitas kesehatan maupun vendor pengembang aplikasi harus memiliki akun untuk dapat mengakses web service BPJS melalui platform [TrustMark](https://dvlp.bpjs-kesehatan.go.id:8888/trust-mark/main.html) dan pembuatan akun tersebut memerlukan izin dari BPJS Kesehatan.

Kami telah melakukan pencarian untuk aturan khusus yang berlaku bagi pengembang library, baik di mesin pencarian maupun di situs TrustMark itu sendiri namun tidak menemukan informasi yang relevan. Kami juga telah mengajukan pertanyaan di forum yang disediakan oleh BPJS, namun sayangnya tidak ada tanggapan yang diberikan. Berikut ini adalah tangkapan layar pertanyaan yang kami sampaikan.

![image](https://github.com/ssec-llg/jkn/assets/25121822/58fc8b20-fdd1-4412-b46e-ad8d6ec4ebad)

![image](https://github.com/ssec-llg/jkn/assets/25121822/dde0be97-d9a1-4989-8406-7bd892d92a00)

![image](https://github.com/ssec-llg/jkn/assets/25121822/6740a112-6d23-4934-bf94-dc8617ad1fce)

Link diskusi: https://t.me/c/1673837525/33014

Oleh karena itu, saat ini kami berasumsi bahwa tidak ada aturan khusus yang mengatur pengembangan library untuk web service BPJS ini, sehingga kami melanjutkan pengembangan library tersebut dengan sah.

Beberapa library serupa atau aplikasi:
- Library PHP https://github.com/virusphp/bridging-bpjs - [contoh](https://github.com/search?q=repo%3Avirusphp%2Fbridging-bpjs+SEP%2F&type=code)
- Aplikasi SIMRS https://github.com/mas-elkhanza/SIMRS-Khanza - [contoh](https://github.com/search?q=repo%3Amas-elkhanza%2FSIMRS-Khanza%20%2FSEP&type=code)
- Library PHP https://github.com/aamdsam/bridging-bpjs - [contoh](https://github.com/aamdsam/bridging-bpjs/blob/dev/src/VClaim/Sep.php)
- Library Python https://github.com/morizbebenk/flask-bpjs
- Dan [lainnya](https://github.com/search?q=bridging%20bpjs&type=repositories)

**Comment by wepe17** [comment]
Mas @mustofa-id untuk get data SEP (Cari) kenapa tetap undifined ya mas, padahal sudah pakai nomor SEP dummy dan prod tapi tetep undifined. Mohon pencerahannya mas.
Terimakasih

**Comment by mustofa-id** [comment]
> padahal sudah pakai nomor SEP dummy dan prod tapi tetep undifined

Sebelumnya sudah terbit SEP? Lebih baik lampirkan cuplikan kode, pesan error, atau log console.

**Comment by wepe17** [comment]
> > padahal sudah pakai nomor SEP dummy dan prod tapi tetep undifined
> 
> Sebelumnya sudah terbit SEP? Lebih baik lampirkan cuplikan kode, pesan error, atau log console.

SEP sudah terbit mas.
![image](https://github.com/user-attachments/assets/97efb9e2-a233-4d57-bc83-f85836a15676)

**Comment by wepe17** [comment]
> > padahal sudah pakai nomor SEP dummy dan prod tapi tetep undifined
> 
> Sebelumnya sudah terbit SEP? Lebih baik lampirkan cuplikan kode, pesan error, atau log console.

SEP sudah terbit mas.

```
import jkn from './jkn.js';
// const cariData = jkn.vclaim.sep.cari();
const resReferensi = await jkn.vclaim.sep.cari({
	nomor: '0208R0060724V00-edit'
});
console.log(resReferensi);

response
{
  metaData: { code: '201', message: 'Data Tidak Ditemukan' },
  response: null
}
```

**Comment by mustofa-id** [comment]
Responsenya valid dari WS. Kemungkinan nomor SEP keliru. Coba cek nomor SEP dari riwayat kunjungan pasien mas.
`jkn.vclaim.monitoring.riwayatPelayanan({ ... })`

**Comment by wepe17** [comment]
> Responsenya valid dari WS. Kemungkinan nomor SEP keliru. Coba cek nomor SEP dari riwayat kunjungan pasien mas. `jkn.vclaim.monitoring.riwayatPelayanan({ ... })`

tetep tidak muncul mas

req:
```
import jkn from './jkn.js';
const resReferensi = await jkn.vclaim.monitoring.riwayatPelayanan({
	/** nomor kartu JKN/BPJS peserta */
	nomorKartu: '000020165-edit',
	/** tanggal awal dengan format YYYY-MM-DD */
	awal: '2024-08-21',
	/** tanggal akhir dengan format YYYY-MM-DD */
	akhir: '2024-08-23'
});
console.log(resReferensi);
```

res:
```
{
  metaData: { code: '201', message: 'Data Tidak Ada' },
  response: null
}
```

**Comment by mustofa-id** [comment]
Itu pesannya tetap valid dari WS mas. Coba cek data peserta dengan nomor kartu tersebut. Pastikan token (cons id, key, secret) sesuai dengan mode (dev/prod) api-nya. Pastikan juga data testing merupakan data yang diberikan oleh pihak BPJS setempat.

**Comment by ssec-dev** [comment]
Untuk penggunaan Postman silakan merujuk ke dokumentasi API atau TrustMark dari BPJS. Silakan buat issue baru untuk pembahasan yang berbeda dan tidak terkait dengan issue ini. Mohon untuk tidak off topic.
